#!/usr/bin/python3

from nautical.location.point import Point
from nautical.io.parse import *
import geocoder

"""
This is a test program to grab some relatively simple information near Virginia Beach.
Get the data for the nearest buoy to Virginia Beach, but make sure that we only get 
a buoy that is in the water. The nearest buoy is actually at Cape Henry and is not
in the water. Print out the data about this buoy and the current sea state.
"""

# buoys = get_buoys_information(False)
#
# # Virginia Beach
# p = Point(36.8529, -75.9780)
#
# print("Searching for NOAA Data Near {}, {}".format(p.lat, p.lon))
#
# in_range_buoys = {}
# for key, value in buoys.items():
#     if p.in_range(value.lat, value.lon, 500000):
#        in_range_buoys[key] = value


buoys = get_buoys_information(True)

"""
Get my current location based on the ip address. We should technically wrap this 
as any failure to find an ip address will fail here
"""
g = geocoder.ip('me')

if g.lat is not None and g.lng is not None:

    print("Searching for NOAA Data near {}, {}".format(g.lat, g.lng))
    p = Point(g.lat, g.lng)


    closest_buoy = None

    #from math import inf

    closest_distance = float('inf')
    close_point = None

    for key, value in buoys.items():

        distance = p.get_distance(value.lat, value.lon)

        if distance < closest_distance:
            closest_buoy = key
            closest_distance = distance
            close_point = value

    print("Closest buoy id = {} [{}, {}]".format(closest_buoy, close_point.lat, close_point.lon))


# buoy = 44099
#
# data = buoy_workup(buoy)
#
# print("CURRENT WAVE DATA")
# print(data.present_wave_data)
#
# print("CURRENT SWELL DATA")
# print(data.present_swell_data)
#
# print("PAST DATA")
# [print(x) for x in data.past_data]
