# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Code Coverage

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
        python -m pip install coverage-badge
    - name: Install Project and Applications
      run: |
        python -m pip install . --upgrade
    - name: Setup Git
      run: |
        git config --global user.name "Brent Barbachem"
        git config --global user.email "barbacbd@dukes.jmu.edu"
    - name: Execute the tests and push results
      env:
        token: ${{ secrets.CI_TOKEN }}
      run: |
        pytest --cov=tests
        mv .coverage .cov/
        pushd .cov
        rm coverage-badge.svg
        coverage-badge -o coverage-badge.svg
        popd
        git ls-files --modified | xargs git add
        git commit -m "[Automated Commit]: Adding code coverage information from unit tests." || echo "no changes to commit"
        git remote set-url --push origin https://barbacbd:$token@github.com/barbacbd/nautical || echo "no need to set remote"
        git push --force || echo "nothing to push"
