name: Publish Project Pages to Github

on: 
  release:
    types: [released]
permissions:
  contents: write

jobs:
  build-pages:
    name: Build and Publish Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Git 
      run: |
        git config user.name "Brent Barbachem"
        git config user.email "barbacbd@dukes.jmu.edu"

    - name: Commit The Docs
      run: |
        git checkout master
        git pull
        git checkout gh-pages
        git rebase master
        git pull

        # remove all current docs                                                                                                                                                                                          
        git rm -rf docs/

        # Grab my own script used for documentation, and make it executable                                                                                                                                                
        wget https://raw.githubusercontent.com/barbacbd/tools/main/scripts/docs/auto_doc.sh
        chmod +x auto_doc.sh

        # used for the current copyright year. Didn't want to keep changing it manually                                                                                                                                    
        export YEAR=`date +'%Y'`

        # execute the script passing some github variables as well as static variables                                                                                                                                     
        ./auto_doc.sh nautical nautical "Brent Barbachem" ${{ github.event.release.tag_name }} $YEAR

        # remove files that are not needed - don't leave as artifacts                                                                                                                                                      
        rm -rf nautical.egg-info
        rm -rf build
        rm -rf auto_doc.sh

        # Add all of the current files                                                                                                                                                                                     
        git add docs

        git commit -m "Adding Documentation changes for release ${{ github.event.release.tag_name }}"
        git push origin gh-pages

      
