# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build-Linux

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - edited

jobs:
  systems-tests:
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}}-${{matrix.python-version}}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package with test dependencies
        run: |
          python -m pip install -e ".[test]" --upgrade
      - name: Tests
        run: |
          pytest --cov=nautical
